### PR TITLE
migrate frontend to new version

### PR DESCRIPTION
**Pull request by jan-xyz**
I removed the old template based frontend with the javascript version that was using the API to trigger visualisation and display the result which was available under `/v2`.

There are no other major changes.

### CODE REVIEW

**Comment by rhsimplex** [comment]
Hey sorry I missed this!  Will look over it within the week.

**Comment by jan-xyz** [comment]
Hey Ryan, do you have feedback on this? :)

**Comment by rhsimplex** [comment]
Looks great! goodbye, my crappy templates :fallen_leaf:

**Comment by rhsimplex** [comment]
I'll push a new release soon

**Pull request merged**
