### PR TITLE
add keras >= 2 and fix some bug

### PR DESCRIPTION
**Pull request by XdpAreKid**
add keras >= 2 and fix some bug

### CODE REVIEW

**Comment by XdpAreKid** [comment]
in keras 2.0,the model can save by model.save() in a hdf5 file

**Comment by rhsimplex** [comment]
Hi @XdpAreKid thanks for your contribution.  I'm on vacation at the moment, but will be back in a couple days.  I believe the tests are failing due to a pytest fixture that is not general enough to support your change, so I'll have a look at it when I'm back in a few days.

Looking forward to merging this first PR :smiley:

**Comment by XdpAreKid** [comment]
Hi,thanks for your reply.But i think my code still have some
problems.There are two ways to save the architecture  and weights of
the model in Keras.The first one is model.save(),the other is
model.to_json() to save the architecture of a model and
model.save_weights() to save the weights of a model.I don't solve this
problem.Maybe we can add a button in layout.html to choose which ways
we save the model.

2017-05-23 23:46 GMT+08:00, Ryan Henderson <notifications@github.com>:

**Comment by rhsimplex** [comment]
Ah I see.  So what we really need is for the loader to try each possibility.  Is there a way to do that without the user specifying the saved model type?

**Comment by rhsimplex** [comment]
@XdpAreKid looks good! Just a few minor mostly cosmetic comments. Also needs an additional test, so we don't reduce coverage: I can recommend something.

**Comment by rhsimplex** [comment]
can you add this to the end of `tests/test_picasso.py`:

```python
class TestKerasModel:

    def test_saved_model(self):
        # tests that KerasModel can load from a saved model
        import tempfile
        from picasso.ml_frameworks.keras.model import KerasModel

        data_path = os.path.join('picasso', 'examples',
                                 'keras', 'data-volume')

        km = KerasModel()
        km.load(data_path)

        temp = tempfile.mkdtemp()
        km.model.save(os.path.join(temp, 'temp.h5'))

        km = KerasModel()
        km.load(temp)

        assert km.tf_predict_var is not None
```

**Comment by rhsimplex** [comment]
Great!  If you can just address the style comments to make this PEP8 compliant, I'll merge it.  Let me know if you have any questions.

**Comment by XdpAreKid** [comment]
OK,i'll commit soon

**Comment by rhsimplex** [comment]
There were a couple other small changes.  I went a head and made a PR against your branch with the fixes (https://github.com/XdpAreKid/picasso/pull/1), so just merge that in your branch and we should be set to merge here

**Comment by XdpAreKid** [comment]
If you change the BaseException to ValueError,you'll get the problem that you both have Json file and H5 file(architecture and weights).

**Comment by rhsimplex** [comment]
Yes but doesn't BaseException catch both anyway? At least this way if something else goes wrong, it will error out as expected.

It is annoying that it's not more fine-grained, we could improve that -- but I don't want to hold up your PR forever.

**Comment by rhsimplex** [comment]
Merged! Thanks again.

**Comment by XdpAreKid** [comment]
you're welcome 
------------------ Original ------------------

**Pull request merged**
