### PR TITLE
Add jquery frontend

### LINKED ISSUE #24: Rewrite web app views to use API calls
Following the merge of #18, we can now vastly simplify the web application (and testing) by making sure we use the proper API routes.  Also should follow #23

### PR DESCRIPTION
**Pull request by jan-xyz**
This Pull Request adds the frontend at `127.0.0.1:5000/v2` as a single page web app. I tried to mimic the original website as much as possible in terms of elements.

fixes #24

### CODE REVIEW

**Comment by jan-xyz** [comment]
Hi @rhsimplex, do you have any feedback on this?

**Comment by rhsimplex** [comment]
If I go to `http://127.0.0.1:5000/v2/` and chooise partial occlusion with 10 strides and window size of .30, i still get the default (2 strides, 0.50 occlusion), even after I clear the cache.  Can you reproduce?

Any thoughts about automated testing for the javascript code?

**Comment by rhsimplex** [comment]
Also, sorry I didn't get to this sooner :grimacing:

**Comment by jan-xyz** [comment]
Uh, sorry that this slipped through. I will have another look at the parameter hand over from the API to the backend. 

I will need to check how I can check that code. In the end I would like to have a Selenium integration test but maybe some unit testing for the JavaScript part wouldn't hurt.

**Comment by jan-xyz** [comment]
@rhsimplex , I corrected the problem you found and updated the pull-request.

I also thought about unit testing the Javascript part and testing the Front-end in general.

As I see it there are three things I'd like to test:
1. Javascript (if no objection I will use QUnit https://qunitjs.com)
1. Integration Test of the entire thing (I already started looking into Selenium and will continue, it seems like a good choice)
1. How do we know if the output is correct? (You saw it manually now that the images weren't correct, I'd like to automate that part. How deterministic is the output from the visualizers? Is it stable enough to compare it with an image diff? https://stackoverflow.com/questions/29261009/carrying-out-unit-testing-in-python-on-a-method-that-implements-imagedraw

**Comment by rhsimplex** [comment]
Yes you can _definitely_ use an image diff.  That would be a really great unit test that would probably prevent a lot of bugs.

I defer to your judgement on how to do front end testing.  When you make a decision let me know and I'll try to help you integrate it into our CI.  Maybe open a new issue if you want to discuss more =)

Is this PR ready for review or are you still planning some other stuff?

**Comment by jan-xyz** [comment]
I have a half working Selenium test in there. If you don't mind having it in master (it is currently disabled) then it's good to go. We can discuss the remainder in the new ticket (#42).

**Comment by jan-xyz** [comment]
#43 and #44 are also two tickets I created based on this discussion. I would start working on these tickets as my next project!

**Comment by rhsimplex** [comment]
Ok cool! I'll look through as soon as possible

**Comment by rhsimplex** [comment]
Sorry for the delay, leaving for Christmas Monday and tons to do as usual =)

**Comment by jan-xyz** [comment]
This PR now also includes tests for #42 and #43 in a crude manner. The integration tests just check if the website builds up and the image diff tests are inspecting one set of settings and the default settings.

The integration tests are currently not part of the pipeline since I don't want to mess around with the `.travis.yml` too much. They can be run with `pytest integration_tests` if Firefox 57 and the correct `geckodriver` is installed. The travis file is already prepared for it and I would add the command to the script section if you permit.

**Comment by jan-xyz** [comment]
It looks like the reference images are exceeding the disk quota for travis docker images.

**Comment by rhsimplex** [comment]
Interesting -- is Travis still giving you problems? Do you want me to re-review now?

**Comment by jan-xyz** [comment]
Ready to review :)

**Comment by rhsimplex** [comment]
Classy stuff! I can't provide much review on the frontend files, but everything else looks good to me.

Next PR: replace the old frontend with this one??

**Comment by jan-xyz** [comment]
Sounds good, I'll add some more Selenium tests when doing the PR to make sure the frontend is properly tested.

**Pull request merged**
