### PR TITLE
add tensorflow test

### PR DESCRIPTION
**Pull request by rhsimplex**
Per #7

### CODE REVIEW

**Comment by rhsimplex** [comment]
@scopelf Can you see if this branch fixes the issue please?

**Comment by scopelf** [comment]
Hi Ryan,
this fixes the problem of models with names "XXX.cpkt" + extension such as model.ckpt-12312. However, there is still the problem that the search mask -
latest_ckpt_fn = max(glob.iglob(os.path.join(data_dir, '*.ckpt*')), key=os.path.getctime) 
- not excludes *.meta* files. For some reason, the multinets' *.meta* file has a more recent timestamp and it's name does also include *.ckpt* and is thus wrongly selected as checkpoint file. I suggest, excluding *.meta* files in the search mask for the checkpoint file. However, since "glob" does not support exclusions, I suggest to filter the findings (not really elegant):
latest_ckpt_fn = max([i for i in glob.iglob(os.path.join(data_dir, '.ckpt')) if not ".meta" in i],
key=os.path.getctime) 
Best,
Filippo

**Comment by rhsimplex** [comment]
Ok, that **should** do it

**Comment by rhsimplex** [comment]
I went ahead and merged, because we need the test for other PRs.  If there's still an issue we can fix it later.

**Pull request merged**
